# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
group :development, :test do
  gem 'pry-byebug', '~> 3.7'
  gem 'rspec', '~> 3.9'
end
